#!/usr/bin/env node
/* RaphaAtlas — sitemap builder.
   Run:  node build_sitemap.cjs      (or: npm run build:sitemap)

   Emits a sitemap *index* (sitemap.xml) pointing at one file per section,
   rather than a single flat list. Google treats each child sitemap as a unit it
   can report on separately in Search Console's Sitemaps panel, so "calculators
   are indexed but guides are not" becomes visible at a glance instead of being
   averaged away across every URL on the site.

   lastmod is taken from the file's last git commit date, never from "now" —
   a lastmod that moves every time the build runs is noise Google learns to
   ignore, and it is the one field in a sitemap that is a factual claim.

   Adding a page: put its slug in the right SECTION below. check_integrity.cjs
   reconciles both directions, so a page missing here fails the build. */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = __dirname;
const ORIGIN = 'https://www.raphaatlas.com';

/* Sections are ordered as a reader would meet them: what the site is, the tools
   it is known for, then the reference guides, then the trust and policy pages. */
const SECTIONS = [
  {
    file: 'sitemap-pages.xml',
    label: 'Home and company pages',
    urls: [
      { slug: '', priority: '1.0', changefreq: 'weekly' },
      { slug: 'about', priority: '0.6', changefreq: 'yearly' },
      { slug: 'contact', priority: '0.6', changefreq: 'yearly' },
      { slug: 'medical-review-board', priority: '0.7', changefreq: 'yearly' },
      { slug: 'editorial-policy', priority: '0.7', changefreq: 'yearly' },
      { slug: 'privacy', priority: '0.3', changefreq: 'yearly' },
    ],
  },
  {
    file: 'sitemap-calculators.xml',
    label: 'Calculators',
    urls: [
      { slug: 'calculators', priority: '0.9', changefreq: 'monthly' },
      { slug: 'macro-calculator', priority: '0.9', changefreq: 'monthly' },
      { slug: 'body-type-calculator', priority: '0.9', changefreq: 'monthly' },
      { slug: 'bac-calculator', priority: '0.9', changefreq: 'monthly' },
      { slug: 'conception-calculator', priority: '0.9', changefreq: 'monthly' },
    ],
  },
  {
    file: 'sitemap-guides.xml',
    label: 'Topic guides',
    urls: [
      { slug: 'health', priority: '0.8', changefreq: 'monthly' },
      { slug: 'nutrition', priority: '0.8', changefreq: 'monthly' },
      { slug: 'fitness', priority: '0.8', changefreq: 'monthly' },
      { slug: 'lifestyle', priority: '0.8', changefreq: 'monthly' },
    ],
  },
];

const fileFor = slug => (slug === '' ? 'index.html' : `${slug}.html`);

function lastmod(slug) {
  const f = fileFor(slug);
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', f], { cwd: ROOT, encoding: 'utf8' }).trim();
    if (out) return out;
  } catch { /* not a repo, or file never committed */ }
  return fs.statSync(path.join(ROOT, f)).mtime.toISOString().slice(0, 10);
}

let wrote = [];
for (const section of SECTIONS) {
  const body = section.urls.map(u => {
    const missing = !fs.existsSync(path.join(ROOT, fileFor(u.slug)));
    if (missing) throw new Error(`${section.file}: "${u.slug}" has no file (${fileFor(u.slug)})`);
    return `  <url>
    <loc>${ORIGIN}/${u.slug}</loc>
    <lastmod>${lastmod(u.slug)}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`;
  }).join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${section.label} — generated by build_sitemap.cjs, do not edit by hand -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
  fs.writeFileSync(path.join(ROOT, section.file), xml);
  wrote.push(`${section.file} (${section.urls.length} urls)`);
}

// The index's own lastmod per child is the newest page inside it.
const index = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Sitemap index — generated by build_sitemap.cjs, do not edit by hand.
     One child sitemap per section so Search Console reports coverage per
     section instead of averaging it across the whole site. -->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${SECTIONS.map(s => {
  const newest = s.urls.map(u => lastmod(u.slug)).sort().pop();
  return `  <sitemap>
    <loc>${ORIGIN}/${s.file}</loc>
    <lastmod>${newest}</lastmod>
  </sitemap>`;
}).join('\n')}
</sitemapindex>
`;
fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), index);

console.log('sitemap.xml (index) ->\n  ' + wrote.join('\n  '));
